### ISSUE TITLE
Push pre-release V4 Bootstrap-Sass gem

### ISSUE THREAD

**Issue by kkirsche** [twbs/bootstrap#17291]
X-Ref: #17290

I think it'd be great to have a pre-release version released. Pre-release gems can be released as such:

Source: http://guides.rubygems.org/patterns/#prerelease-gems

Many gem developers have versions of their gem ready to go out for testing or “edge” releases before a big gem release. RubyGems supports the concept of “prerelease” versions, which could be betas, alphas, or anything else that isn’t ready as a regular release.

Taking advantage of this is easy. All you need is one or more letters in the gem version. For example, here’s what a prerelease gemspec’s version field might look like:

```ruby`\
Gem::Specification.new do |s|
  s.name = "bootstrap-sass"
  s.version = "4.0.0.alpha.1"
```
Other prerelease version numbers might include `2.0.0.rc1`, or `1.5.0.beta.3`. It just has to have a letter in it, and you’re set. These gems can then be installed with the `–pre` flag, like so:

```shell
% gem list bootstrap-sass -r --pre

*** REMOTE GEMS ***

bootstrap-sass (4.0.0.alpha.1)

% gem install bootstrap-sass --pre
Successfully installed bootstrap-sass-4.0.0.alpha.1
1 gem installed
```

**Comment by glebm** [comment]
Have we decided on how we deal with this yet? If the gem is published from the repo, it should include the sprockets asset-url hack. Perhaps it would be cleaner to have separate repos for each framework/distribution (bootstrap-sprockets, bootstrap-compass, bootstrap-mincer, etc).

**Comment by kkirsche** [comment]
@glebm that's a fair point. I guess my ultimate point is I'd love to see a pre-release gem. I personally think it makes more sense to use Elastic's style of making separate gems and have a gem which pulls them all together this allows people to take them as needed. E.g. https://rubygems.org/gems/elasticsearch

**Comment by glebm** [comment]
@kkirsche You mean separate gems for separate components? The components are not loaded in RAM, sounds like too much overhead for saving 50KB of disk/network in 2015.

**Comment by kkirsche** [comment]
No, I meant bootstrap-core (main library), bootstrap-mincer with the mincer integration pieces, bootstrap-compass with the compass integration pieces, etc.

**Comment by glebm** [comment]
Mincer is only usable from node. For ruby, there are only 2 options: bootstrap-sprockets and bootstrap-compass. They only differ in https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/_bootstrap-sprockets.scss vs https://github.com/twbs/bootstrap-sass/blob/master/assets/stylesheets/_bootstrap-compass.scss, but I suppose having different gems would make sense. Until someone uses compass with sprockets, and pulls the wrong gem (bootstrap-compass would be the wrong one).

**Comment by kkirsche** [comment]
Fair enough. You have more experience with SASS gems so I'll defer to you. My experience lies in deploying more complex gems that can be compartmentalized in a way that probably isn't as simple for a front-end framework.

**Comment by glebm** [comment]
Just realized that none of these hacks are necessary anymore because we do not provide glyphicons. The ruby gem can be published directly from this repo. I'll get a PR going.

**Comment by kkirsche** [comment]
Thanks @glebm — not sure what needs to be done but figure it relies on an admin ultimately to push it so figured best for someone else to take care of this.

**Comment by glebm** [comment]
I am not going to push the gem until we decide on the best way to do this, just doing some experimental work.

**Comment by glebm** [comment]
Note that there is ongoing work in the bootstrap-sass repo, so you can use that branch if you want to try it out with your ruby project: https://github.com/twbs/bootstrap-sass/pull/954

**Comment by kkirsche** [comment]
@glebm thanks. I wouldn't be able to push to it though since not part of the core team for any of the repos. I made https://github.com/kkirsche/bootstrap_migrator though for now just waiting to hear from mdo about how he wants a focused example then I'll build it and provide a gem for the core team to try out and see what they think

**Comment by glebm** [comment]
Thoughts after looking through everything carefully:

* Bootstrap rubygem would need to take care of the sprockets manifest, sass setup, compass templates,  rubygem-specific tests, and a ruby-specific Readme section. This is quite a few files that have to be at specific paths. I've tried adding them here and it's lots of clutter.

* bootstrap-sass codebase can be used to provide all these things, and there is a work in progress that nails it: https://github.com/twbs/bootstrap-sass/pull/954.

Therefore, here is what seems like a good course of action:

* [ ] Create a new repo: bootstrap-rubygem, based on the https://github.com/twbs/bootstrap-sass/pull/954, that would provide a rubygem that can be used standalone, or with sprockets or compass.
* [ ] Update the docs.
* [ ] Publish the alpha.

@twbs/team Thoughts?

**Comment by cvrebert** [comment]
So, would we be publishing separate `bootstrap-sprockets` and `bootstrap-compass` gems from the same repo (`bootstrap-rubygem`)?
Anyway, the main point about separating out `twbs/bootstrap-rubygem` from `twbs/bootstrap` SGTM.

**Comment by hnrch02** [comment]
> So, would we be publishing separate bootstrap-sprockets and bootstrap-compass gems from the same repo (bootstrap-rubygem)?

I believe that would no longer be necessary since we ditched Glyphicons - Sprockets required some sort of "asset-url hack", as @glebm mentioned earlier.


> Anyway, the main point about separating out twbs/bootstrap-rubygem from twbs/bootstrap SGTM.

Agreed. We already have too many files in this repo anyway.

**Comment by thomas-mcdonald** [comment]
@glebm Will it break anything if we just rename bootstrap-sass -> bootstrap-rubygem?

**Comment by glebm** [comment]
@cvrebert Best keep them in the same gem, as having 2 would be confusing for those who use sprockets *with* compass. The compass-specific part now is just the template (manifest + variables), so it's no maintenance burden.

@thomas-mcdonald We would break all the package managers pulling directly from the repo (bower), and everyone relying on the repo directly.

**Comment by glebm** [comment]
Meanwhile, trying to get the bootstrap gem name: http://help.rubygems.org/discussions/questions/9220-reporting-abuse-on-bootstrap

**Comment by JanStevens** [comment]
As the creator of the MR that adds alpha support, my 2 cents:

- You don't need separate versions, since there are no glyphicons anymore. Adding a readme section on how to include different alternatives (there is a font awesome gem for example)
- Basically the gem comes down to pull bootstrap branch and save it in the right locations and make sure it integrates easily into rails/sprockets/compass

What could be added:
- Rake/Rails task for installing bootstrap or one of its variants (flex/grid/reboot)
- Rake/Rails task to copy over the variables.scss file so people can start overwriting

**Comment by cvrebert** [comment]
@twbs/sass So, https://rubygems.org/gems/bootstrap/versions/4.0.0.alpha3 and https://github.com/twbs/bootstrap-rubygem are now things. We still need to add an entry for the Gem to http://v4-alpha.getbootstrap.com/getting-started/download/ , but other than that, are there any remaining TODOs here?

**Comment by glebm** [comment]
Everything is done, now it's just the docs :+1:

**Comment by cvrebert** [comment]
Closed by #18597.
