### ISSUE TITLE
v4: Examples

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#18465]
Meta tracking issue for todos on our docs examples.
### Carousel
- [ ] #17878: Missing controls
### Dashboard
- [x] #17816: Overall dashboard layout is fubared (need to refactor it all)
- [x] #17883: Spacing on page header is less than ideal
### Justified nav
- [ ] #17723: Shit's fucked, likely needs refactor
### Offcanvas
- [ ] #17173: Broken nav
- [ ] #19832: Incorrect sidebar hiding at `sm` viewpoint

**Comment by mdo** [comment]
Only thing remaining on this list is #19832. Will follow up on that separately.
