### ISSUE TITLE
v4: Cards

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#18468]
Meta tracking issue for card updates.

- ~~#17274: Nuke last-child stuff for margin utils~~
- [x] #17959: Images and widths not matching up
- [x] #17911: Nuke the margin-bottom from cards in favor of margin utils
- ~~#17528: Responsive card groups?~~
- [x] #17511: Cards on small screens
- [x] #17398: Missing some card classes in docs
- ~~#17395: Tables in cards (woof, probaby going to punt because this is just panels all over again)~~
- [ ] #17287: Contrast in cards too low?
- [x] #17244: Card variants and text-muted less than ideal
- [ ] #17159: Accordion example should use cards
- [x] #16934: Add support for cards with tabs
- Nuke `card-border-radius-inner`?

**Comment by petetnt** [comment]
I created a PR for `card-*-outline` variant documentation @ #18501

**Comment by Johann-S** [comment]
With this PR : https://github.com/twbs/bootstrap/pull/18400 accordion use Cards

**Comment by mdo** [comment]
Have most of these addressed—closing out for now. Will tackle the rest later.
