### ISSUE TITLE
v4: Grids

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#18471]
Meta tracking again.

- [x] #17119: Missing flexbox docs
- [x] #17122: Vertical alignment
- [x] #17131: Flex auto width?
- [x] #17228, #17261: New base class?
- [x] #17310: IE10 and IE11 are broken with flex
- [ ] #17481: Custom grid gutters per breakpoint
- [x] #17512, #17514: Mixin changes
- [x] #17586: Skip containers when grid classes are disabled
- [ ] #17593: Document variables changes in migration
- [x] #17603: use of -12 with flex?
- [ ] #17694: Fluid images and flex don't mix in FF
- [x] #17756: Flex wrapping bug
- [ ] #17982: Broken grid when only using grid file?
- [x] #18024: Flex and justify
- [x] #18036: Drop -offset-12?
- ~~#18054: Container widths greater than media queries~~
- [x] #18164: More flex helpers
- ~~#18207: Flush containers?~~
- ~~#18407: Block grid?~~
- [ ] #18420: Firefox 1/11 flex column setup wraps

**Comment by cvrebert** [comment]
* [ ] #18746: Minimum container/viewport width?

**Comment by mdo** [comment]
Not everything is done here, but closing out for no as the bulk is being handled in #19099.
