### ISSUE TITLE
Getting to v4

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#20631]
Long story short, v4 has taken far too long and I know we're struggling to find enough time to make significant dents across the open issues and PRs. To help get through it all, I'm calling it on v3 and outlining the big steps remaining here so folks know what's in store.

Here's how we get from a string of alphas to a finalized v4 release:

- [ ] **Stop all work on v3—today.** The open issues, split dev setup, and more holds us back from focusing entirely on v4. I'll close all remaining `v3` issues and milestones. Any new changes to v3 will be sporadic and highly irregular.

- [ ] **Switch v4-dev to the default branch.** Building on step one, this makes `v4-dev` the code you see when you visit the repo. I'll cut a `v3-dev` branch and leave `master` as-is until v4 ships.

- [ ] **Move the docs sites.** The biggest pain will be moving our docs pages around (specifically, moving `v4-alpha.getbootstrap.com` to `getbootstrap.com`). The current v3 docs will be moved to a sub-directory like our other hosted versions.

- [ ] **Ship some betas.** After the alpha releases take care of the major breaking changes, we'll ship some beta releases to work out the final kinks before RC and final releases.

There's a ton this list misses, but these are the broad strokes that get us to v4. Holler with any questions or comments as I push us through this.

/cc @twbs/team

**Comment by cvrebert** [comment]
> The current v3 docs will be moved to a sub-directory like our other hosted versions.

@mdo But this shouldn't break any links, right? We just need to keep things under `/<version number>/` directories for v4 going forward.

**Comment by AdamHess** [comment]
A large part of the community thinks this is premature and a terrible idea until bootstrap 4 is released. 

I personally have not started working with bootstrap 4 explicitly because it is still in Alpha. I as many others would still benefit from fixes, tweaks or features until bootstrap 4 is completely released. 

see more discussion: 
https://www.reddit.com/r/web_design/comments/51cfo4/bootstrap_v3_is_no_longer_maintained/

**Comment by julianlam** [comment]
@AdamHess I feel a large part of the negative sentiment in that reddit submission was due to a selective bias present in the title: "Bootstrap v3 is *No Longer Maintained*", like @mdo and @cvrebert decided to set everybody adrift and wave goodbye, when this obviously isn't the case.

As @mdo has pointed out, commits to v3 will still occur, just irregularly and likely only when needed.

It's all really in how you look at it... *No Longer Maintained*, vs *Declared Stable*

Bootstrap v3 has been used in production for a very long time (relative to web development timelines, anyway). I think it's more than ready to be put into maintenance mode, so proper attention and TLC can be given to v4.

**Comment by shankariyerr** [comment]
@mdo It is a bold move. Provided that it is taking longer than usual to get v4 out of alpha, it is a much needed decision.

**Comment by mdo** [comment]
Thanks for the feedback, y'all.

I'm sorry that I didn't explain more of the context around why I made this decision. It's been a long time coming given how sporadic development of any kind has been lately. Shipping Alpha 4 today was all the motivation I needed though to make a big change so we can push this over the finish line.

So, here's some context for why I made this decision.

- Every one of us working on Bootstrap has a full-time gig. I hate leading with this, but my job at GitHub takes up the majority of my time. Sucks, but that's the way it is with open source.

- **[Bootstrap 3 was released over three years ago.](http://blog.getbootstrap.com/2013/08/19/bootstrap-3-released/)** My closing of all those issues—most of which have been untouched for months to a year—has nothing to do with how many people use it today, or tomorrow, or ever again in the future. Please, I highly encourage you to keep using it!

- **[The first alpha of Bootstrap 4 was release over a year ago.](http://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/)** We're super far behind on that and it clearly shows in just about every aspect. In that post I also mentioned we'd maintain v3 for the foreseeable future. I think over a year has been long enough honestly; the web has changed quite a lot since v3 was released.

- There have been over 3,200 commits to v4 since development started on it. The first commit to the v4 branch was back in March of 2015. I've been working on this "new release" for over a year and half :\, and it's terribly frustrating knowing that I've not shipped it yet.

- Maintaining two versions of a large codebase is incredibly taxing. We tried to do it for over a year and it's just bogged us down further with every issue and PR. Something had to give to push the project forward, and active v3 development was it.

- The last v3 release was [v3.3.7](http://blog.getbootstrap.com/2016/07/25/bootstrap-3-3-7-released/) back in July and it barely saw any changes. The only one of importance was jQuery 3 support. Before that, the last release was in November of last year. We've been punting on all new features and non-critical changes since the first alpha came out.

- The codebases are completely different: **v4 has 120,000 lines of changes across ~600 files.** There's little chance the same exact issues affect both versions, however those that have, I left open (or were reopened) as appropriate.

Please don't take this as ungrateful or negative in any way. I'm still flabbergasted and honored that so many people use something I helped create. I'm super fortunate to be able to work on something with so much reach.

I love working on Bootstrap and helping people make rad shit on the web. Let's get v4 out the door and build even more amazing things <3.

**Comment by andyl** [comment]
Great news.  V3 is stable.  I'm really looking forward to V4.

**Comment by alexbowers** [comment]
@julianlam I don't think the title I chose was bias, since  the first bullet point states "Stop all work on v3—today"

**Comment by yarl** [comment]
@mdo `ISSUE_TEMPLATE.md` should have info about it. Something like: "no more v3 bugs".

**Comment by ChrisF79** [comment]
In the words of the great Jersey Shore cast from a decade ago... "You do you" as well as "Haters gon hate."

**Comment by AdamHess** [comment]
@mdo

thank you for your thorough response. 

1. delegate more, or get more maintainers. There are 100,000 stars, im sure some of them would be capable of contributing. 
2. length of time simply means neglect, it would be like measuring code quality by using LOC.
3. again delegation. remember, you can't do everything. Ask for volunteers rather than waiting passively for them. 
4. 3,200 commits. Why hasn't there been a formal release cut from it? Maybe cut out a few features for this version and include them in the next point release. 
5. yay for jQuery 3, but good delegation on punting on new features for 3. (fixes should still go in) 
6. do you think we're going to have a python 2/3 or angular 1/2 issue. Don't you think it would be prudent to just rebrand this product as something else as it has devolved away from the original project substantially. While I get the whole semver thing, (major releases cause breaking changes) if there is so much change that major release breaks "all the things" it may as well be noted as a completely different product if a substantial amount of time is spent relearning the framework.

**Comment by geori** [comment]
It's about time! :)  We've been using v4-alpha in production for six months.  It works great but it just feels icky to include "v4-alpha" in our package.json.

**Comment by jeveloper** [comment]
This can be resolved fairly simply:

Two plans:
1. Startups/individual developers - $19.99/year 
2. Enterprise/Companies with 30+ ppl - $399.99/year

I know of so many banks and companies that use bootstrap for their internal and external products and this would be an easy write off for them. Plus it might attract more paying customers due to support.

I'm a big fan of semantic Ui (i recommend) as bootstrap slowed down in progress.

I'll be happy to build licensing platform for bootstrap , stripe has subscription system.

This is normal and i think makes sense.

Thank you

**Comment by TheBuzzer67** [comment]
I'm developing on v4-alpha and If I find any problem, I'll let you know! Thanks for you good work, we're backing you gang! So hurry like everyone to see v4 released but it better take your time before to release!

I just read post about Wordpress, I want to introduce BS in my next themes so don't forget about tags that can make confusion between plateformes!

**Comment by jcutrell** [comment]
I'd like to address something quite out in the open:

The fact that @mdo and others have full time jobs *does not actually suck.* It is a good thing that @mdo is employed and isn't just making free things all the time, because GitHub is super useful and we all want @mdo to have money in the bank. We should be celebrating the opportunity in the field, not taxing open source maintainers because of their "pesky day-job." Day jobs are a big reason things like Bootstrap exist to begin with.

Secondly, there are always tradeoffs when it comes to software. Hopefully that's not a surprise. As it turns out, the decision to leave v3 behind is presumably one of pure economics. Does it make more sense to string v3 alongside v4 for another half-year than to cut losses and move forward? For the maintainers of the project, who have the full rights to make these decisions, the answer is a resounding "nope." And perhaps the most important aspect of it all is that if you so choose, you can hit the "fork" button and continue accepting pull requests. Nothing is stopping that from happening.

(I realize the value of those pull requests coming into the original account, but again - the economics don't make sense.)

The real question you have to ask yourself if you're a developer is whether or not you trust @mdo and co that the loss of maintenance on v3 is worth it for the added energy on v4. Trust is the cornerstone of open source in the first place.

Finally, if you are concerned about v3 no longer being maintained and v4 not being "stable", remember we are talking about front-end frameworks here. While stability and predictability are Good Things™, the worst thing that could happen with v4 alpha may be an edge case browser bug (that will almost certainly be fixed when v4 actually ships) or re-naming of classes - but even then, you have the power to fix it yourself, because it's ultimately CSS and JavaScript.

**Comment by arackaf** [comment]
I see people "thumbs-downing" @jeveloper's comment, but I'd like to also say, I'm fairly sick and tired of people not paying a dime to use OSS, and then presuming to bitch and moan to maintainers when decisions they don't agree with are made.

In an ideal world we'd be paying to see this stuff for commercial applications.  Unfortunately that's not the world we live in.

If v3 is stable and the devs want to push toward v4, then great.  Thank you all for all the work you've done on Bootstrap.

**Comment by nfeld9807** [comment]
@arackaf I don't think it would be a good direction to have a personal / individual license. It would halt the use of bootstrap relatively fast. I'm in support of an enterprise license or a fee if you include bootstrap into something you package and sell.

**Comment by arackaf** [comment]
@nfeld9807 - I explicitly said for **commercial use**.

If you're making money while using Bootstrap, why in the world should you not have to pay for it?

**Comment by zanardigit** [comment]
Totally agree about the pragmatic approach and just cut off tasks that you cannot actually take care of. As long as this "drop the stable version for an unstable version" does not become an habit, it's ok for me.

Also agree on finding a way to get some money out of it (subscriptions for additional features, support, explicit donations).

I cannot help but wondering why v4 is a complete rewrite compared to v3. Was that a wise choice, especially considering this is a part-time project? I'm all for small changes, so maybe new features should have been delivered in smaller steps instead.

**Comment by jcutrell** [comment]
@arackaf an open source project is something that is done in public, and thus it effects other people.

Have you ever been upset with someone who was driving poorly? Swerving near your car, running red lights, or going slow in the fast lane? Why were you upset? Their actions were affecting you, right?

Now, let's apply the same logic here. An open source project, while often benefitting those around you, is a social contract. And when the contract becomes large enough, when enough people are involved, a maintainer's decisions start affecting more than just their self. This is why trust is the cornerstone of OSS, and why you can't take an open source project lightly.

You aren't paying the people around you to drive how you want them to drive, and yet you are justified to be upset with them when they drive poorly, because their actions are affecting you.

All of this said, I don't think @mdo is managing this poorly at all. I just think he's going a route that some people prefer, and other's don't. It's not dangerous, but rather it's opinionated.

**Comment by arackaf** [comment]
@jcurell - you describe precisely why OSS maintainers get burned out.

Lots and lots and lots of people start using a project, not paying a dime to do so, and then they suddenly get to start making demands and having expectations of what the maintainers do, what directions they take the project, etc?  Ridiculous. 

This is why we need licensing.  Paying customers get to say which direction a project should head.  Paid maintainers would be happy to listen.

**Comment by shankariyerr** [comment]
I agree with @arackaf and @jcutrell

**Comment by joshmanders** [comment]
@jcutrell Except using Bootstrap doesn't endanger your life, so that comparison is moot.

Fact of the matter is, Mark and team have spent countless hours of their free time working on this without any compensation. If they want to discontinue support on v3 and move forward on v4 it's their rights and nobody, not me, not you, not even Google can say otherwise. **Period**.

If you do not like the decision, it's open source, it's MIT licensed. Fork the repository and maintain v3 yourself. If that's too much for you to do, think long and hard about what you're saying and apply the same logic to the maintainers of bootstrap.

Nobody owes any of us anything. Get over it.

**Comment by r-tanner-f** [comment]
> ...the negative sentiment in that reddit submission was due to a selective bias present in the title: "Bootstrap v3 is No Longer Maintained"

If it's just spin, maybe don't close so many issues by leading with:

> Bootstrap 3 is no longer being officially developed or supported.

This sounds exactly like "No Longer Maintained" to me, or at least, the difference is trivially. Not that there's anything wrong with that.

**Comment by stephenbe** [comment]
I think it would be interesting to open a [patreon](https://www.patreon.com/) account. With financial support, I think it would help advance the project further and maybe even have an actual employee that could help with the project full time.  What do you think @mdo ?

**Comment by jcutrell** [comment]
@joshmanders Well, it's not really moot per se, because someone driving slow in the fast lane is merely an inconvenience. But perhaps that's not the most effective metaphor.

Also, **I agree with you** - hopefully my more recent comment about open source affecting peoples' lives doesn't override my [previous comment](#issuecomment-244958750) about this being totally in @mdo's hands, ideologically and literally. I'm personally quite happy about the decision to leave behind v3, and have been using v4 for a bit now.

I bring up the fact that open source isn't just a "maintainers do whatever they want and no one is allowed to say anything" situation. This discussion shouldn't be about entitlement, because no one is entitled to control over Bootstrap except the creators of the project. It's about relationship. 

Telling people they can't be upset over something that is affecting the work they do is just as ludicrous as saying that @mdo should have to do whatever those people want him to do. Either side of the equation gets muddy and underserves the point of open source: sharing, trust, and relationships.

When you start an open source project and regularly maintain it, and lead others to depend on you, then yes - you still have full rights to shut that project down. You can litter your code with bugs. You can do whatever you want, right? It is *your proejct* after all. But that doesn't mean everyone should love you for every decision you make. People also have a complete right to disagree with you. They can't dictate your actions, but they can disagree.

Again, I think stopping active development on v3 is a good call, and I'm happy @mdo and co are making these decisions.

**Comment by joshmanders** [comment]
@jcutrell Too many people see Open Source projects as paid software. It's not. You can be upset over Mark's decisions, and that's fine, but you do not need to tell him that he's wrong for his decisions.

Every open source project I release i build for my own usage, if it gains any popularity and people use it, they can contribute to it if they want, but ultimately my decision stands. It's my project and I built it for myself. If I decide to completely ditch an older version for a newer better version, that's my right and nobody can say otherwise, regardless of if it has 5 stars or 100,000 stars on github.

**Comment by craft37** [comment]
Good news!

**Comment by e-oz** [comment]
@joshmanders when OS project have hundreds of commits from community, then maybe community have some rights in this project too. There is difference between "free" and "open source". 

I have great respect to Mark Otto and to all contributors of this project, I respect their decisions and I, personally, don't use twbs 3 anymore, but I still think old issues have right to not be closed, maybe somebody from the community will decide to solve them later. 

From other side, maybe they can fork twbs3 and call it "twbs for oldies", something like that ;)

**Comment by tomhodgins** [comment]
> @joshmanders said:
> If you do not like the decision, it's open source, it's MIT licensed. Fork the repository and maintain v3 yourself. If that's too much for you to do, think long and hard about what you're saying and apply the same logic to the maintainers of bootstrap.

This is so beautiful. There's a giant FORK button up in the top left…it's the reason this website (Github) exists!

**Comment by joshmanders** [comment]
@e-oz Having them open or closed doesn't matter, closing an issue does not make it null and void, it just means that from now on, the team can focus on v4 issues.

If anyone here is adamant on maintaining v3 and wants those issues, fork the repo, turn issues on, and I will gladly write a program for you that will import all `v3` labeled issues into your repo.

**Comment by anhskohbo** [comment]
This's good news in today, I have waiting for long time :)

**Comment by AlexSwensen** [comment]
Although im not a contributor to Bootstrap, I am a user, and have used it in countless applications. With v3 considered stable by myself and many i have worked with, i agree with the decision to move forward on v4.

I do want to say that i do not agree with the licensing model proposed. Sure it would be great if some income was made by commercial use of Bootstrap, but i think that would also kill a lot of its use and so much of why it has become so popular. 

Those are just my bits. Overall I'm very happy with the direction this is going!

**Comment by twbs-closer** [comment]
Temporarily locking this issue due to social media links.

**Comment by mdo** [comment]
_First time I've seen our closer bot do that—sorry for prematurely locking this._

Reiterating and expanding on a few things:

- **There are absolutely no plans to charge for Bootstrap. Ever.**

- **v3 remains 100% usable and stable.** We're not going to actively maintain it so the limited time we do have can go to v4's development. And to be clear, we've barely maintained v3 for the last year, accepting only critical fixes and docs updates.

- There are countless things I wish I'd done differently with v4's development, but the best way I know how to deal with that is to push forward.

- **It's not just about the number of open issues and PRs.** Attempting to patch a largely stable three year old code base without introducing new bugs or breaking changes takes a lot of time. Verifying, documenting, and communicating changes takes time. Doing the actual release process takes time.

I'll do my best to keep cranking on v4 and get more stable releases out the door. After that, we can re-address v3's maintenance again.

<3

**Comment by andre-d** [comment]
Could I suggest a a thing maybe?

1) Create a repo called v3-community and assign a few community devs to maintain that.

2) Update the text on the bootstrap site to reflect that v3 is no longer maintained but that v3-community still exists but that Bootstrap guarantees on support for that

This allows Bootstrap to continue to be honest about the level of support, but provides a place for the community to place patches/etc for issues they find along the way Bootstrap does not want to deal with.  

This also paves the way for a community to maintain v3 post-v4 when web applications do not have the resources to migrate to the v4 changes at the various layers.

**Comment by lddubeau** [comment]
@mdo I disagree with the notion that v3 is stable. [Here](https://github.com/twbs/bootstrap/issues/20511) is a regression introduced by v3.3.7. There's no project I know of where this would not be treated as an indication of instability. I disagree with the wholesale closing of the issue that pertain solely to v3. I can understand closing those issues that entail *adding features*, but I don't agree with closing issues that are reporting bugs in the code base.

On the one hand v3.3.7 has unresolved bugs. On the other hand v4-alpha is, well, *alpha*. I don't base my production-ready code on alpha versions of third-party libraries. Bootstrap is not going to constitute an exception to this rule. My projects do not have resources to devote to test-driving alpha code.

**Comment by chrisweb** [comment]
I do agree that saying that v3 is now deprecated, but v4 is still alpha seems like a strange strategy at first. But if you think about it, it's obvious that reducing the time spent on v3 to increase the amount of time available for v4 is a good thing. But it's also obvious that people are now afraid to still use v3 for new projects as it won't get maintained in the future and on the other hand they are also afraid to move on and use v4 as it is still labeled as alpha version. So to decide which version to use today in production, for new projects, is tricky. But I think it's just more a communication problem, then a strategic faux pas ;) 

In my opinion mdo should have said that he will reduce his efforts maintaining v3 to a minimum, so that he can allocate a maximum of time to v4 until v4 reaches the stable status. The day v4 is stable the tickets of v3 could get closed and all the efforts would go into maintaining v4. So for now, people would go on using v3, during the next months several betas of v4 would get released and in early 2017 v4 could be ready and people would start using v4 in production instead of v3.

But still I also understand mdo, he is closing the tickets because managing them takes a lot of time that otherwise he won't have to push v4 forward and I think this is the right decision. I think it's a strong signal, it means that if from now on you start a new project use twbs v4 because v4 is already pretty stable, even though it's still called alpha. It also does not mean that starting at midnight all projects that have been done in the past using twbs v3 will break. 

I see lots of people arguing that he should close all the bugs of v3 before moving on, but I think this is utopic as there will always be new bugs, mostly because browsers will continuously evolve and bring new bugs. Another thing somebody else mentioned previously, this ain't a server side library that might still contain highly critical security issues that if not fixed can be highly problematic for the projects using it. Probably all the critical bugs of twbs have been fixed in the past, those that are left now are probably minor bugs that only affect a small group of users.

I doubt that creating a v3-Community version is a good idea, but everyone that thinks this must be done should just do it and learn from it. Fork the repo and post the link here and on reddit, so that others can join you in your effort. It's that easy. That's the great thing about OSS, if you don't like the direction the maintainers have chosen, then fork it and do your own thing ;) Hopefully a lot of those people that complain on reddit right now, will join and help out maintaining a fork of v3.

The problem with doing a fork, is that with any other OSS project, it won't be successful if you just have a lot of contributors, you will also need one or more strong maintainers. If you don't have one or some good maintainers that dedicate a lot of their time managing the project then it will probably fail. You can't just have a project and let everyone commit whatever pleases him. You will always need maintainers that review the commits and moderate the tickets. 

Letting a project run on it's own will in my opinion never work. You need to have people that know the entire commit history and code base well, to avoid repeating mistakes. Also to avoid accepting a fix that breaks things that have been fixed in the past. You also need to have a vision and decide which features are useful and can be added or which one are only useful for a minority and should exist as addons / plugins but not be part of the core project... Great OSS projects are not great because they are OSS, they are great because their maintainers did a great job maintaining them.

**Comment by andre-d** [comment]
>  it means that if from now on you start a new project use twbs v4 because v4 is already pretty stable, even though it's still called alpha.

Once the site is replaced perhaps something explaining what "Alpha" implies should be made then.

**Comment by smathy** [comment]
Opinions about other people's FOSS projects (what they should and shouldn't do, whether they're justified in calling a version stable, etc.) should come in the form of forks or PRs.

**Comment by martinbeentjes** [comment]
As Bootstrap 3 is quite stable, I think this is a fair decision. I hope that with this decision the development of v4 (and future versions) will move progressively better. I am just wondering, what will happen with bugs regarded to security issues and such? Will those be fixed in the period of v4 Alpha until a release version of v4?

**Comment by mickaelandrieu** [comment]
@mdo good move, did you notice that bootstrap4 is already used for the default theme of the new version of PrestaShop ? As part as the core team, I can tell it's stable enough to be flagged as àma beta :) Also, only bootstrap4 themes can be sold on the official store!

**Comment by AlchemyUnited** [comment]
@mdo  - While I realize there are a tremendous number of moving parts here, is there any way to view a given build more as a series of "dependencies" than a single MASSIVE blob? Quotes are intentional. 

Let me try to explain, quickly.

To say that Bootstrap is robust is an understatement. But how many are using ALL the features ALL the time? If "core" features X, Y and Z are completed then might it be possible to release Build XYZ as "completed" with the understanding P, Q and R are wonky, or not included at all. I mean, the idea that nothing is done until it's all done - for a product this sophisticated - just feels like something even Sisyphus would fear. 

If we are to assume that no one is quitting their day jobs, and that Bootstrap 5.x is only going to be even more consuming (presuming you survive 4), then it seems to me the only thing that's (potentially) p[ossible is to adjust the architecture and how the pieces are integrated,, finalized and pushed back out again. 

Pardon me for stating the obvious, but BS5 might kill you & co - if it ever happens at all. Something has to give, and the status quo doesn't seem quite up to the task of this Godzillian endevor. 

p.s. Maybe The Force be with you.

**Comment by AlchemyUnited** [comment]
@andre-d - Nice. That just makes sense. If 3.x is gonna be left for dead by BS then why not just hand it off now? Good thinkin'. Now we know why they pay you the big bucks ;)

**Comment by flyingsandal** [comment]
@andre-d - The problem with that then becomes branding;  you have to segment it enough that the community knows the actual team responsible for Bootstrap is not responsible for the "community" version.  3.x is stable, functioning, and works amazing.  Bring on 4.x!

**Comment by dreyks** [comment]
What's all the hype? v3 is stable for the 99% of the use cases. The thing is those 1% edge cases that resulted in issues are not guaranteed to be present in v4 branch, so if the team is scarce on resources, moving forward is a sensible decision.
* If you are using 3.x happily and plan to move to 4.x when it becomes stable, this will now happen sooner
* If you are using 3.x happily and don't plan to move to 4.x ever what does it matter to you then?
* If you are using 3.x and everything is fine except one that pesky bug that prevents your app from shining then why don't you spend a little time apart from your full-time job and fix this bug. You're a web-developer after all, arnt ya?

Even moving from alpha to beta will be a big deal, cause many libraries that depend on bootstrap (say react-bootstrap) don't even want to start working on v4 compatibility as it is still in alpha for a year and nothing is clear about its future

The community helps the product progress but the community does not own it. The community cannot dictate the product owners how to spend their free time. And for those who say it is against the OSS principals I say it **is** OSS at its core: you get it for free, you can help make it better, but you can't demand anything from it

**Comment by AlchemyUnited** [comment]
@flyingsandal - A concern, but feels minor at best. As @andre-d noted, there are probably some not at all interested in going to 4.x. For them, a living 3.x makes a lot sense. "Branding" should solvable.

**Comment by claudiordgz** [comment]
![giphy 2](https://cloud.githubusercontent.com/assets/779325/18295832/be79459a-7472-11e6-8cd8-74a3b5eb40d1.gif)

Thanks for the heads up, we use bootstrap 3 on one project and **never** update it, that project will eventually get written bottoms up with something else.

On another project we are using v4-alpha, we update it often and take heat from managers constantly (it's an alpha version omg!!) 

I want to thank you @mdo and the entire bootstrap team for working hard for this. I hope my comment motivates other bootstrap lovers to come forth and say thanks since most of them will be a quiet bunch.

**Comment by Studio384** [comment]
Is there any - at least vague - ETA on when the first beta will be available? Will Alpha 6 be the final alpha, or will there be more?

**Comment by braginteractive** [comment]
v4 is taking longer than the MacBook Pro update..

**Comment by mdo** [comment]
> v4 is taking longer than the MacBook Pro update

@braginteractive MacRumors has the last release date for the MacBook Pro at 1,549 days ago, whereas v4 work was started ~530 days ago and the first v4 alpha was 384 days ago. I think we have a bit of wiggle room on hitting that point just yet. :trollface:

**Comment by deepu105** [comment]
Thank you @mdo and other twbs members. You guys are doing the community a huge favor :+1:

**Comment by niutech** [comment]
Doesn't your decision to stop bugfixing v3 contradict the pledge from [Bootstrap 4 alpha announcement](https://blog.getbootstrap.com/2015/08/19/bootstrap-4-alpha/)?

> **Supporting v3**
> 
> When we shipped Bootstrap 3, we immediately discontinued all support for v2.x, causing a lot of pain for all our users out there. That was a mistake we won’t be making again. For the foreseeable future, **we’ll be maintaining Bootstrap 3 with critical bug fixes and documentation improvements.** v3 docs will also continue to be hosted after v4’s final release.

**Comment by julianlam** [comment]
I would imagine *critical* being the key word here. If a commit was made to v3 that contained a showstopper regression, I would imagine they would roll it back or fix it properly.

**Comment by jp7677** [comment]
PS: Could you please mark alpha4 and 5 as pre-release on github like you did with earlier alphas? The latest release should still be 3.3.7 imho.

**Comment by BobbyBabes** [comment]
> ... we're struggling to find enough time to make significant dents across the open issues and PRs. 

At the moment I see only one open PR for v3 when I filter with ``is:pr is:open label:v3 ``
Have you hidden the other open PRs for v3?

I'm asking because I still have one WP theme built with BS v3. Everything is OK with that theme.
But of course I have not used every component of BS in that theme. So if I would add a new component, and it has a quirk or bug, I would like to possibly help myself by looking at still pending/open v3 PRs.

**Comment by rafalp** [comment]
@BobbyBabes p'much they locked all issues and pr's that were focused at v3.

**Comment by cvrebert** [comment]
> Have you hidden the other open PRs for v3?

GitHub has no such feature. The PRs for v3 have almost completely been dealt with already. Most were closed as WontFix for the reasons explained earlier in this issue.

**Comment by BobbyBabes** [comment]
@rafalp @cvrebert Thanks for clearing that up. I didn't realise that the open PRs were all closed with "WontFix". I'll treat the closed v3 PRs with ``WontFix`` as not yet in BS v3 then.
I just want to be able to look into the actual PRs that are not in v3 yet. Just to fix stuff myself when required.

**Comment by jipexu** [comment]
@ BS dev team : you make a great job ! thanks for that ... I agree that is time to focus the entire energy on the beta4 following by BS4 !

BS 3 was a very good tool who no need more time to spend ..
We use BS 4 alpha xxx  in several of our site across our CMS  (since months) and it's just perfect ... except the change on each alpha .. ;-)   ... but this is the game ... (... and we wait also to make a new beta version of our CMS)

I know the time needed for such project and one more time THANKS for the team !

**Comment by m1guelpf** [comment]
Updates?

**Comment by rafalp** [comment]
@m1guelpf there are plenty in other milestones and issues for you to find out ;)

**Comment by MargateSteve** [comment]
Looking back through this, although licensing would bring in some cash there is no doubt overall usage would drop and people would just start torrenting it. That said, with ad-blockers, advertising revenue is probably very little in comparison to the usage and time spent developing it.
Why not start selling submitted Bootstrap sites or components (think Themeforest/Codecanyon and the like)? It would make sense for things built with Bootstrap to be sold on the site and the the team to get some of the money in return.

**Comment by AlchemyUnited** [comment]
@MargateSteve said "...no doubt overall usage would drop and people would just start torrenting it...."

Well, in the context of the current no product revenue stream at all, it's not like such a drop in usage would mean a drop in revenue ;)

Why can't there be a premium license for commercial usage? I can't image how, say $25 a pop would be too much for most reasonable companies to handle. Even a $100 developer's lifetime license might fly.

FWIW, Radiohead made more money on "In Rainbows" than all their previous major label releases combined. In Rainbows was when they did a "pay what you want" model. Certainly @mdo & co is as talented as Thom Yorke & Co.

**Comment by coliff** [comment]
@AlchemyUnited @MargateSteve 
MDO and team have already stated (more than once) that there are absolutely no plans to start charging for commercial usage. For that those don't know already; if anyone _really_ wants to financially support some of the team there are optional Bootstrap themes which add additional components, utilities and plugins: https://themes.getbootstrap.com/collections/all

**Comment by MargateSteve** [comment]
@AlchemyUnited I meant to say 'OR people will start torrenting it'. I agree with what you say that any income would be better than none but ong and short is that I do not think charging (appreciating @coliff's reply that there are no plans to) would be the best option. Anything that has to be paid for get torrented and with that they also get hacked, amended or virus-riddled, meaning what someone thinks is Bootstrap is an unstable clone and the brands name gets tarnished.  Also, I am not in a financial position to drop $25 each time I have an idea!

@coliff I have seen those and they are very nice, however only a ridiculously devoted Bootstrap fan would shell out $99 when you can get similar, packed to the brim with a host of open source plug-ins already integrated, for $25 on Themeforest. When you see the sales numbers of some of the templates on there, it seems madness that Envato are making a fortune from templates built on Bootstrap while Mark and the team get nothing.

**Comment by AlchemyUnited** [comment]
@MargateSteve - I wish I had $5 for every forum posts that starts "I have a problem with ______. I bought it on ThemeForest..." :) 

Would a lower price sell more? Sure! Does more = better (over the  long term)? Not necessarily. $99 might be too rich for some, but at the same time the value is probably well in excess of $99. 

Perhaps we need a movement (?) similar to "fair trade" (for coffee)? The point being (provided the $74 delta doesn't kill you) there is  a difference between the $99 to the team makes the magic happen, and $25 to the dude/dude-ette downstream that stands on the shoulders of those giants. Mind you, it should probably be obvious. But I'm pretty sure it's not. It's not just what you pay, but also who you pay.

**Comment by rafalp** [comment]
So you have fulltime job and sideproject that's opensource that you work for fun/satisfaction or out of personal feeling of obligation to "the community". Now you decide to commercialize your OS project too and start charging for it.

Now you are working two jobs, each with people you now have real obligation to because money is involved. And because money is involved your bank is involved, or paypal, or law, or tax office.

Thats how "great idea" it is to try charge for your side project in addition to doing regular one.

**Comment by patrickhlauke** [comment]
also, and maybe i'm naive/missing something: if this became a paid-for project, what would the incentive be for non-team-members to contribute? and how would revenue be split across team members? etc. anyway, i believe this idea was nixed ages ago, so no point in dredging it out further...

**Comment by mdo** [comment]
Bootstrap is always going to be open source. I'll put that to bed right now :).

Also going to lock this to prevent it going off the rails again. This issue isn't about that—it's to let folks know our plans for how we'll ship this stuff. See the opening comment for an updated plan—I've made some decisions on URL structure and what not with #22716 in progress.

Getting closer!
