### ISSUE TITLE
Tab JS and .active class

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#21223]
There are a ton of issues all surrounding the `.active` class applied via our tab JS. I'm collecting all of them here to try to de-dupe them and figure out a path forward.

Here's what I have so far (checked indicates closed issue):

- [ ] #18566, #19374, #20523, #20797: `.active` tab state isn't removed on tab switch with `<nav>`-based structure (but does work on `<ul>` one). #20039 tries to fix this with some new JS, but perhaps not the right direction we want to go (see below).
- [ ] #20451: Scrollspy adds `.active` to `.nav-link`, but the nav docs have it on `.nav-item`.
- [ ] #20620: Tabs JS doesn't work with list groups unless you add `.nav-item` to the parent.
- [x] #21021, #21036: Rename `.active` to `.show` (previously `.open`) for dropdowns.

Seems like this is all stemming from the flexibility I was trying to provide by allowing `.active` to be placed on parent items (e.g., `<li>`s) or the `.nav-link` itself. To resolve this, I think we need to only allow `.active` on the `.nav-link` (or in the case of list groups, `.list-group-item`). With dropdowns, we also need to have a separate class that is added to the parent or menu to properly show that.

My proposal is this:

- Let's allow this to be flexible for any markup by applying the `.active` class *only* to the item itself, and not the parent.
- Nav links, list group items, and dropdown triggers get `.active` on the `<a>` or `<button>` for their active state.
- Dropdown triggers get `.active` to indicate their associated menu is shown, and the `.dropdown-menu` gets `.shown` to indicate it is visible.

That last part is a deviation from the current behavior, and might require more work. I'd be fine keeping `.show` or `.shown` on the parent of the dropdown trigger and menu if that'd be easier.

Thoughts @cvrebert, @bardiharborow, @Johann-S?

---
Potentially related tabs issues and PRs for context:

- [x] #17371, #17642, #20039, #20523: Dropdown items get stuck in `.active` state.
- [ ] #19849, #20174, #20795: Tabs are opened even if disabled.
- [x] #21055, #21056: Rubber band scrolling can remove active nav link.

**Comment by mdo** [comment]
I've pushed a branch to add a basic `<nav>`-based demo to the docs fwiw. See b05f148.

**Comment by mdo** [comment]
Also /cc @Starsam80 because his PR at #21036 addresses the double active state problem outlined in #21021. His PR addresses the proper class naming for that issue, and could likely be built upon further after merge with the issues outlined here.

**Comment by Starsam80** [comment]
Actually, just so you know, my PR (#21036) is just a roundabout way of renaming `.in` to `.show`, ruining the purpose of #20982/#19344, and really only meant as a temporarily fix. I'll take a look at this once I'm done my other fixes and see if I can do something better.

**Comment by vanduynslagerp** [comment]
See PR #21807 for all the fixes mentioned above, except #20620 (see [comment](https://github.com/twbs/bootstrap/pull/21756#issuecomment-274352106).)
