### ISSUE TITLE
Restore icons on valid/invalid form states as optional styles

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#22762]
#22395 is removing the icons for now (to limit scope), so we'll need to restore those in a later release. We'll need to tackle some other issues, so I'm consolidating and referencing all of those here. Hoping to get to it in Beta 2, but it might wait to a patch or minor bump.

- [ ] #22670: Icon should be positioned from the top for textareas
- [ ] #22696: Sometimes icons don't appear in inputs in modals in Edge
- [ ] #19852: Custom selects mess up icon size due to custom background-image for the caret

**Comment by jimjaeger** [comment]
@mdo Hi Mark, can you look on the comment in #22762. Can we reopen #22762 or may can you look into as part of this item here?

**Comment by mdo** [comment]
We should also consider replacing the &times; icon with something else, as noted in #23274.
