### ISSUE TITLE
Move v4-dev to master

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#26951]
Let's get back to `master` being our default branch. This might screw a ton of things up, so holler at me if we should hold off. I'm hoping to do this alongside v4.2.

- Ensure `v3-dev` has everything from `master`
- Delete existing `master`
- Switch to `v4-dev`, then `git co -b master`
- Push new `master` branch
- Delete `v4-dev`

And then, the docs and settings:

- [ ] Make `master` default branch again
- [ ] Update links across docs
- [ ] Update links across readme

**Comment by stof** [comment]
Missing step before deleting the v4-dev branch: update the target of all opened PR to target master rather than v4-dev (otherwise, all these PRs would get closed by the branch deletion)

**Comment by mdo** [comment]
v3 work to fix XSS stuff moved to `master`, so closing out.
