### ISSUE TITLE
Remaining to do after the jQuery removal

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#28342]
- [x] Update plugin pages
  - [x] Carousel - still has a few references to `$()` (#28768)
  - [x] Collapse - still has a few references to `$()` (#28768)
  - [x] Dropdown (#28768)
  - [x] List group
  - [x] Modal (#28768)
  - [x] Navs (#29181)
  - [x] Popover (#28768)
  - [x] ScrollSpy (#29181)
  - [x] Toasts (#28779)
  - [x] Tooltip (#28779)
- [x] Other doc pages
  - [x] getting-started/browsers-devices.md (#28779)
  - [x] getting-started/javascript.md (#28768)
- [ ] Various
  - [x] Add a section explaining that it's possible to use this version with and without jQuery
  - [x] Search docs for `jquery` (not case sensitive) and `$(`
  - [x] Replace https://codepen.io/Johann-S/pen/djJYPb or add a codepen with vanilla JS (#32163)
  - [ ] Maybe explain when an element is considered visible in the scrollspy callout
  - [x] See if we really need `DOMContentLoaded` anymore in tests and docs. #28337
  - [x] Remove `If you’re building our JavaScript from source, it requires util.js.` not needed anymore (#28779)
  - [x] Remove https://twbs-bootstrap.netlify.com/docs/4.3/getting-started/browsers-devices/#android-stock-browser after #28317 or in that branch (#28779)

**Comment by midzer** [comment]
I am trying to help and port "Replace https://codepen.io/Johann-S/pen/djJYPb or add a codepen with vanilla JS" item

This is what i got until now:
https://paste.headstrong.de/view/08ba7d0b

Too bad I can't test properly, because `bootstrap` object is not found (I've included https://github.com/twbs/bootstrap/blob/master-xmr-v5/dist/js/bootstrap.bundle.js)

**Comment by Johann-S** [comment]
Hi @midzer, thank you for trying to tackle that, but you should wait for our first alpha release

**Comment by moliata** [comment]
> Hi @midzer, thank you for trying to tackle that, but you should wait for our first alpha release

Do you have an ETA when the first alpha is going to be released?

**Comment by alpadev** [comment]
Since the alpha has been released - some updated codepen without the jQuery dependency: https://codepen.io/-alpa-/pen/PoZWzNM

I used querySelectorAll in that case, to keep the logic from the corresponding jQuery example - although I'm not sure if that's adding some confusion. Also to keep things DRY I used a wrapper function for document.querySelector that is named $ - that is what Chrome is doing by default in case $ is undefined - but might be a bit confusing too.

Anyways I guess it'd be better if you add this to your codepen, to keep things streamlined.

**Comment by XhmikosR** [comment]
@Johann-S what's the status of this? Only 2 TODO are left :)

**Comment by Johann-S** [comment]
@alpadev can you submit a PR with your CodePen link?

**Comment by alpadev** [comment]
Sure if you are ok with the updates.

**Comment by alpadev** [comment]
To get this list done. What would be the required information for the "Maybe explain when an element is considered visible in the scrollspy callout" todo?

Like an element is considered visible `if scrollTop >= offset` or that an element is considered visible if the target element has a valid getBoundingClientRect with either width or height not being 0?

**Comment by XhmikosR** [comment]
@alpadev it's been a while but IIRC the issue was about https://getbootstrap.com/docs/4.5/components/scrollspy/#non-visible-target-elements-ignored:

>#### Non-`:visible` target elements ignored
>
>Target elements that are not [`:visible` according to jQuery](https://api.jquery.com/visible-selector/) will be ignored and their corresponding nav items will never be highlighted.

**Comment by alpadev** [comment]
Oh I see. I had a look into the code and in theory one could hide it with `visibility: hidden;` (and maybe `height: 0;`) and it would still work, though being barely visible :)

So there's nothing I can help here with I guess?

**Comment by XhmikosR** [comment]
I don't recall TBH, I know I removed the docs part so that we move forward back then, but I don't know if the statement applies to v5 (it probably does, though).

**Comment by XhmikosR** [comment]
So, only the scrollspy callout is left 🙂

Now, I'm not sure how to proceed with this, but if we can put it back quickly explaining when an element might not be visible and that scrollspy will ignore it, I think that would be the best solution.

PRs welcome!

**Comment by alpadev** [comment]
@XhmikosR uhm there is some info about the visibility: https://github.com/twbs/bootstrap/blob/main/site/content/docs/5.0/components/scrollspy.md#non-visible-target-elements-ignored
It could be extended though, if you see a benefit from it.

**Comment by XhmikosR** [comment]
Oh, true. I guess we can finally close this issue.

Thanks everyone for the help!

**Comment by AndreasA** [comment]
The package.json file still has jquery as devDepencency. If it is not required anymore, it should not be there anymore.

https://github.com/twbs/bootstrap/blob/v5.0.2/package.json#L125
https://github.com/twbs/bootstrap/blob/v5.0.2/package.json#L55
