### ISSUE TITLE
Remaining JS linting TODO

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#28455]
* [x] simplify one-line multi-line imports when we have one thing we import.
* [ ] take care of the max-depth warning in button.js
* [ ] enable `no-mixed-operators` rule
