### ISSUE TITLE
v5: Branches to rebase from Hugo move

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#28482]
Starting this per @XhmikosR's suggestion. These are all my branches that _might_ need rebasing, but I need to review them and see.

### @mdo branches

- [x] #28265: Drop .media 
- [x] #28266: Carousel improvements for easier customization
- [x] #28267: Drop hover query
- [x] #28268: Updated colors spike
- [x] #28317: Browser support
- [x] #28339: RIP print styles (need to fix and keep `d-print`)
- [x] #28447: Prevent form validation mixin from generating invalid CSS
- [x] #28449: Docs dark mode
- [x] #28450: Forms update
- [x] #28458: Badges update
- [x] #28461: Drop some mixins
- [x] #28463: Input-based button groups
- [x] #28472: Docs migration page

**Comment by XhmikosR** [comment]
I'm gonna take care of those later or tomorrow. If there are more let me
know.

**Comment by XhmikosR** [comment]
OK, I rebased all of them.

Some you could have rebased yourself since they had no doc changes :P

Now, in case you hit any issues, CC me on the PR. I will go through this one more time in the next days to make sure I didn't miss anything, but should be fine for now.
