### ISSUE TITLE
Actions CI TODO

### ISSUE THREAD

**Issue by XhmikosR** [twbs/bootstrap#29232]
- [x] Cache npm dependencies (for master caching `~/.npm/` or similar should be enough), but invalidate them if package.json or package-lock.json change (for Node.js 6.x we need to cache `./node_modules/` instead)
- [x] Make sure we are using the latest stable Chrome at the time - We need to cache this somehow otherwise it slows us down a lot **EDIT:** this seems to be updated automatically in the image
- [x] Official README.md badge
- [x] Link to actions in README badge? -  Not sure if this makes sense since other people don't see this, at least not now
- [ ] Bring back `skip browser` filter of commit messages so that it's possible to skip BrowserStack tests for a commit. On Travis we did:
  ```sh
  if [[ "$TRAVIS_NODE_VERSION" = "10" && "$TRAVIS_EVENT_TYPE" = "push" && ! `git log --format=%B --no-merges -n 1 | grep '\[skip browser\]'` ]]; then npm run js-test-cloud; fi
  ```
- [x] Add `fast-fail: false`
- [ ] ~~v4-dev: can we do a conditional command in `run`? We need to do `npm install` only if we are on Node.js version less than 8, else we need to do `npm ci`~~
- [ ] There's no way to restart a single job
- [ ] There is no way to restart a successful job/workflow
- [x] **Duplicate jobs when we merge a PR**, at least on master
- [x] **Run bundlesize for fork PRs too** - see #29276
- [ ] See if it's possible to have Coveralls or even BrowserStack run for fork PRs

**Comment by XhmikosR** [comment]
I'm going to close this now since most issues are solved.
