### ISSUE TITLE
Tracking: CSS Variables

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#35319]
Putting together this tracking issue to set up a checklist of components that we should migrate to using CSS variables.

## Globals

- [x] Body font, color, and background
- [x] Theme colors
- [x] Border
- [x] Accent backgrounds
- [ ] Spacing

## Content

- [ ] Typography
- [ ] Tables
- [ ] Figures

## Forms

- [ ] Inputs
- [ ] Selects
- [ ] Checks, radios, and switches
- [ ] Range
- [ ] Input group
- [ ] Floating labels
- [ ] Layout
- [ ] Validation

## Components

- [x] **Accordion**
  - Slated for v5.2.0
  - #35861
- [x] **Alerts**
  - Added in v5.2.0
  - #35401
- [x] **Badges**
  - Added in v5.2.0
  - #35402
- [x] **Breadcrumb**
  - Added in v5.2.0 (originally slated for v5.3.0)
  - #35403
- [x] **Buttons**
  - Added in v5.2.0
  - #34600
- [x] **Cards**
  - Slated for v5.2.0 
  - Coming in #36059
  - Early spike in #35097 by @tagliala
- [x] **Dropdowns**
  - Added in v5.2.0 (originally slated for v5.3.0)
  - #35409
- [x] **List group**
  - v5.2.0
  - #35862
- [x] **Modal**
  - Slated for v5.2.0
  - #36060
- [x] **Navs & tabs**
  - Slated for v5.2.0
  - #36061
- [x] **Navbar**
  - Added in v5.2.0
  - #34443
- [x] **Offcanvas**
  - Added in #35736
- [x] **Pagination**
  - Added in v5.2.0
  - Previous attempt in #31685
  - #35399
- [x] **Placeholders**
  - _Not yet started, but not all that helpful? Likely skipping for now._
- [x] **Popovers and Tooltips**
  - Currently in progress
  - Slated for v5.2.0
  - #34622
- [x] **Progress**
  - Added in v5.2.0
  - #35962
- [x] **Spinners**
  - Added in v5.2.0
  - #35960
- [x] **Toasts**
  - Added in v5.2.0
  - #35961

## Utilities

- [x] **Background and color utilities**
  - Added in v5.1.0
  - #34100
- [x] **Border utilities**
  - Added in v5.2.0
  - #35428
- [ ] Spacing

## Helpers

- [x] Colored links
- [ ] Ratio
- [ ] Stretched link
- [ ] Vertical rule

---

- #33320: Update `border-color` utils to match background/text changes like in #34100
- #34983: See about adding new global variables that get used unless there’s a component variable present
- #35783: Improving CSS variables logic

**Comment by ffoodd** [comment]
Simple sidenote after buttons' PR: the stylelint rule regarding empty line before custom properties should probably be disabled globally, as we'll almost always have a `scss-docs` comment before.

**Comment by julien-deramond** [comment]
Are carousels and close buttons not missing in this list?
