### ISSUE TITLE
Tracking: Color modes

### ISSUE THREAD

**Issue by mdo** [twbs/bootstrap#37549]
Calling out some outstanding todos and questions from #35857 as we'll merge that PR and tackle these things in smaller batches.

### General todos
- [ ] **Colors/Sass/CSS vars**
	- [ ] Can we generate the new subtle bg, subtle border, and text emphasis colors from `$theme-colors`?
	- [ ] Do we provide hex colors, `rgba()` colors, or both for the new variables?
	- [ ] Document dark mode variables in `css-variables.md`
- [ ] **Forms**
	- [ ] Improve form validation colors
	- [ ] Consolidate approach to multiple background images and CSS vars for form control, check/radio/switch, form-select
	- [ ] Document changes to form validation map, mixin, bg image setting, and general colors
- [ ] **Dropdowns**
	- [ ] Deprecate `.dropdown-menu-dark`? If so, mention in Migration
- [ ] **Navbars**
	- [ ] Double check form field styling
	- [ ] Update togglers to use inline SVGs now instead of embedded ones? If so, mention in Migration
- [ ] **Accordion**
	- [ ] move icons into HTML as SVGs as well? similar to navbars if so
- [ ] **Utilities**
	- [ ] Confirm if we like the inverted box shadow utilities
	- [ ] Refactor new bg, border, and text utilities to use `rgba()` values? TBD on this, would change a lot
	- [ ] Document new theme color CSS variables
	- [ ] Document new dark mode Sass vars
- [ ] **Pagination**
	- [ ] `calc()` function in the comparison on L78?

### Q&A
- Why move some SVGs out of embedded CSS?
	- Makes CSS bundle smaller eventually (come v6)
	- Allows for use of inherited color as opposed to fixed colors, which requires repeating the entire SVG embed in CSS (adding to file size)

### Docs todos
- [ ] Drop logo on homepage on mobile
- [ ] Add color modes section to homepage
- [ ] Audit Migration guide once more
- [ ] Clarify color & bg helpers don't respond to color modes (yet?)
- [ ] Add more examples for color mode specific versions of components? Toasts, for example.
- [ ] Pass color mode to StackBlitz edit buttons?
- [ ] Access color modes in `/examples`?
- [ ] Lighten up the `bootstrap-grid.scss` file by not importing all of `_root.scss`?
- [ ] Linear gradient syntax in docs navbar?
- [ ] New docs navbar SVGs need a11y support
- [ ] Docs navbar dropdown width—move to CSS or keep inline?
- [ ] Unrelated: Streamline JS and CSS banners

**Comment by septatrix** [comment]
Another TODO I would like to add is that this should work without JS (which at least the preview in the PR does not). For the sake of accessibility and js-less users, it should default to respecting the system preferences. Thus, in its current form, the implementation also does not resolve #27514.

I would like to point out that this is the most upvoted comment in the PR (https://github.com/twbs/bootstrap/pull/35857#issuecomment-1282864225), second only to the "Any updates?" comment directly beneath it.

**Comment by XhmikosR** [comment]
Oh, didn't notice we have an issue. Related https://github.com/twbs/bootstrap/issues/37659

**Comment by septatrix** [comment]
> Another TODO I would like to add is that this should work without JS (which at least the preview in the PR does not). For the sake of accessibility and js-less users, it should default to respecting the system preferences. Thus, in its current form, the implementation also does not resolve #27514.

Any update on this aspect? It is not hard to include both mechanisms (`prefers-color-scheme` and `data-bs-theme`) though it obviously increases bundle size a bit. I see that the mechanism can be changed when compiling though only one of them can be selected at once, which is rather limiting. Especially considering that the whole theming mechanism is intended to make it easier to adjust color etc to one's' liking *without* having to compile a custom BS variant.

**Comment by chrisrodkey** [comment]
> Can we generate the new subtle bg, subtle border, and text emphasis colors from `$theme-colors`?

This would be really valuable, for me. This is where I got very confused/lost. I have seen this PR [here](https://github.com/twbs/bootstrap/pull/37737), but that seems to be focused on adding a custom color, and not on how to adapt the `primary` color into `primary-subtle`. This is just where I had to give up on the testing, as I'm just not sure how to proceed. Hopefully the docs can resolve that, but **even more hopefully** there will be a way to set the `subtle` colors automatically via the `$theme-colors`. Otherwise it's going to be a big challenge.

**Comment by carlosalvidrez** [comment]
I suggest classes "bg-light" and "bg-dark" get automatically swapped with the light/dark color mode toggle. Thank you for this great feature.

**Comment by duaneking** [comment]
It should be noted that the examples actually do not include full source, as it's missing javascript files.

**Comment by mellester** [comment]
> 



> > Another TODO I would like to add is that this should work without JS (which at least the preview in the PR does not). For the sake of accessibility and js-less users, it should default to respecting the system preferences. Thus, in its current form, the implementation also does not resolve #27514.
> 
> Any update on this aspect? It is not hard to include both mechanisms (`prefers-color-scheme` and `data-bs-theme`) though it obviously increases bundle size a bit. I see that the mechanism can be changed when compiling though only one of them can be selected at once, which is rather limiting. Especially considering that the whole theming mechanism is intended to make it easier to adjust color etc to one's' liking _without_ having to compile a custom BS variant.

Would a option like `$color-mode-type: data-media-query`  
 that bundles both and fallbacks to media if and only if there is no data-bs-theme set,  be  the thing we need? so no-js will respect the user settings.
